[package]
name = "battle-dinghy"
version = "0.1.0"
description = "Battle Dinghy - Solana Battleship Game"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "battle_dinghy"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
